spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zp943026
    url: jdbc:mysql://47.96.110.108:3306/product?characterEncoding=UTF-8&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8762